export const Tasks = [
  {
    id: 1,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "1/2/2025",
    priority: "low",
    status: "to-do",
  },
  {
    id: 2,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "12/2/2025",
    priority: "low",
    status: "in-progress",
  },
  {
    id: 3,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "12/2/2025",
    priority: "medium",
    status: "done",
  },
  {
    id: 4,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "12/2/2025",
    priority: "high",
    status: "in-progress",
  },
  {
    id: 5,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "12/2/2025",
    priority: "medium",
    status: "to-do",
  },
  {
    id: 6,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "12/2/2025",
    priority: "low",
    status: "done",
  },
  {
    id: 7,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "12/2/2025",
    priority: "low",
    status: "to-do",
  },
  {
    id: 8,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "12/2/2025",
    priority: "medium",
    status: "to-do",
  },
  {
    id: 9,
    title: "Project Dashboard",
    description: "Develop project dashboard",
    createDate: "3/2/2025",
    deadline: "12/2/2025",
    priority: "medium",
    status: "to-do",
  },
];
